---
# TODO: replace this with a proper loop, just loop over a list of hashes
- hosts: 10.100.100.11
  become: true
  tasks:
    - name: Update Host Name [Base Name]
      shell: hostnamectl set-hostname k3s-server-01
    - name: Update Host Name [FQDN]
      shell: hostnamectl set-hostname k3s-server-01.buzzdavidson.com
- hosts: 10.100.100.12
  become: true
  tasks:
    - name: Update Host Name [Base Name]
      shell: hostnamectl set-hostname k3s-server-02
    - name: Update Host Name [FQDN]
      shell: hostnamectl set-hostname k3s-server-02.buzzdavidson.com
- hosts: 10.100.100.13
  become: true
  tasks:
    - name: Update Host Name [Base Name]
      shell: hostnamectl set-hostname k3s-server-03
    - name: Update Host Name [FQDN]
      shell: hostnamectl set-hostname k3s-server-03.buzzdavidson.com

- hosts: rancher_k3s_hosts
  become: true
  tasks:
    - name: Update Apt
      apt:
        autoclean: true
        autoremove: true
        clean: true
        update_cache: true
        cache_valid_time: 3600
        state: latest
        pkg:
          - emacs-nox
          - net-tools
          - htop
          - systemd-timesyncd

    - name: set timezone
      shell: timedatectl set-timezone America/Los_Angeles

    - name: Make sure timesyncd is stopped
      systemd:
        name: systemd-timesyncd.service
        state: stopped

    - name: Delete spurious timesyncd.conf file if it exists
      file:
        path: /etc/timesyncd.conf
        state: absent

    - name: Create timesyncd.conf file
      copy:
        dest: /etc/systemd/timesyncd.conf
        content: |
          [Time]
          NTP={{ ntp_server }}
          FallbackNTP={{ fallback_ntp_server }}

    - name: Make sure timesyncd is started
      systemd:
        name: systemd-timesyncd.service
        state: started

    - name: Disable UFW
      systemd:
        name: ufw
        enabled: no
        state: stopped

    - name: Disable Swap
      ansible.builtin.command: swapoff -a

    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    - name: Reboot instance
      ansible.builtin.reboot:
        reboot_timeout: 600
        post_reboot_delay: 30
