---
- hosts: core_dns_hosts
  become: true
  tasks:
    - name: Wait for all hosts to be responsive
      wait_for_connection:
        timeout: 300

    - name: Update Apt
      apt:
        autoclean: true
        autoremove: true
        clean: true
        update_cache: true
        cache_valid_time: 3600
        state: latest
        pkg:
          - net-tools
          - qemu-guest-agent
          - htop
          
- hosts: proxmox_api_hosts
  vars:
    vm_ids:
      - 10004
      - 10005
  gather_facts: false
  tasks:
    - name: Enable QEMU Guest Agent for DNS VMs
      shell: |
        {% for vm_id in vm_ids %}
        qm set {{ vm_id }} --agent 1        
        {% endfor %}
    - name: Reboot DNS VMs
      shell: |
        {% for vm_id in vm_ids %}
        qm reboot {{ vm_id }}
        {% endfor %}
    - name: Wait for DNS VMs to be responsive
      shell: sleep 30

- hosts: core_dns_hosts
  become: true
  vars:
    ip_address: "{{ ansible_default_ipv4.address }}"
    hostname: "{{ 'core-dns-01' if ip_address == '10.100.100.4' else 'core-dns-02' if ip_address == '10.100.100.5' else fail('Unknown IP address: ' + ip_address) }}"
    fqdn: "{{ hostname }}.buzzdavidson.com"
  tasks:
    - name: Wait for all hosts to be responsive
      wait_for_connection:
        timeout: 300
    - name: Print values
      debug:
        msg: "hostname: {{ hostname }}, fqdn: {{ fqdn }}, ip_address: {{ ip_address }}, current_fqdn: {{ ansible_fqdn }}}}"
    - name: Check if FQDN matches
      block:
        - name: Remove cloud-init package
          apt:
            name: cloud-init
            state: absent
            purge: yes
        - name: Set hostname
          hostname:
            use: debian
            name: "{{ hostname }}"
        - name: Set FQDN in /etc/hosts
          lineinfile:
            path: /etc/hosts
            regexp: "^127.0.1.1"
            line: "127.0.1.1 {{ fqdn }} {{ hostname }}"
            state: present
        - name: Set FQDN in /etc/hostname
          lineinfile:
            path: /etc/hostname
            line: "{{ fqdn }}"
            state: present
        - name: cleanly reboot the host
          reboot:
            msg: "Reboot initiated by Ansible for hostname change"
            reboot_timeout: 300
            pre_reboot_delay: 0
            post_reboot_delay: 5
            test_command: uptime
            connect_timeout: 5
      when: ansible_fqdn != fqdn
