# TODO: add task to poke proxmox to toggle qemu guest agent on for both vms and then restart vms
# TODO: remove reboot step from core_dns_hosts
---
- hosts: core_dns_hosts
  become: true
  tasks:
    - name: Update Apt
      apt:
        autoclean: true
        autoremove: true
        clean: true
        update_cache: true
        cache_valid_time: 3600
        state: latest
        pkg:
          - cloud-init
          - cloud-initramfs-growroot
          - net-tools
          - qemu-guest-agent
          - bind9
          - bind9utils

- hosts: proxmox_api_hosts
  vars:
    vm_ids:
      - 10004
      - 10005
  gather_facts: false
  tasks:
    - name: Enable QEMU Guest Agent for DNS VMs
      shell: |
        {% for vm_id in vm_ids %}
        qm set {{ vm_id }} --agent 1
        qm restart {{ vm_id }}
        {% endfor %}
      register: result

    - name: Show Guest Agent Update Result
      debug:
        var: result
