# TODO: add task to poke proxmox to toggle qemu guest agent on for both vms and then restart vms
# TODO: remove reboot step from core_dns_hosts
---
- hosts: core_dns_hosts
  become: true
  tasks:
    - name: Wait for all hosts to be responsive
      wait_for_connection:
        timeout: 300

    - name: Update Apt
      apt:
        autoclean: true
        autoremove: true
        clean: true
        update_cache: true
        cache_valid_time: 3600
        state: latest
        pkg:
          - cloud-init
          - cloud-initramfs-growroot
          - net-tools
          - qemu-guest-agent
          - bind9
          - bind9utils

- hosts: proxmox_api_hosts
  vars:
    vm_ids:
      - 10004
      - 10005
  gather_facts: false
  tasks:
    - name: Enable QEMU Guest Agent for DNS VMs
      shell: |
        {% for vm_id in vm_ids %}
        qm set {{ vm_id }} --agent 1        
        {% endfor %}
      register: result

    - name: Show result of update operation
      debug:
        var: result

    - name: Stop DNS VMs
      shell: |
        {% for vm_id in vm_ids %}
        qm shutdown {{ vm_id }} -forceStop
        {% endfor %}
      register: result

    - name: Show result of stop operation
      debug:
        var: result

    - name: Wait for VMs to stop
      shell: |
        {% for vm_id in vm_ids %}
        qm wait {{ vm_id }}
        {% endfor %}
      register: result

    - name: Show result of wait
      debug:
        var: result

    - name: Start DNS VMs
      shell: |
        {% for vm_id in vm_ids %}
        qm start {{ vm_id }} 
        {% endfor %}
      register: result
